# -*- coding: UTF-8 -*-
#!/usr/bin/python

NAME_KEY = "recipe_name"
IMAGE_URL_KEY = "recipe_image_url"
URL_KEY = "recipe_url"
RATING_KEY = "rating"
NBR_RATINGS_KEY = "n_ratings"
INGREDIENTS_LIST_KEY = "ingredients_list"
INGREDIENTS_NAMES_KEY = "ingredients_names"
PORTIONS_KEY = "portions"
DIFFICULTY_KEY = "difficulty"
PREPARATION_TIME_KEY = "prep_time"
TAGS_KEY = "tags"
PREPARATION_STEPS_KEY = "prep_steps"
PRIMARY_CATEGORY_KEY = "primary_category"
SECONDARY_CATEGORY_KEY = "secondary_category"
CALORIE_PER_PORTION_KEY = "portion_calorie"
FAT_PER_PORTION_KEY = "portion_fat"
CARBO_PER_PORTION_KEY = "portion_carbo"
PROTEIN_PER_PORTION_KEY = "portion_protein"
